terraform/scaleway-kapsule: docker container_runtine is deprecated
```
Error: scaleway-sdk-go: invalid argument(s): container_runtime does not respect constraint, docker is deprecated. see https://kubernetes.io/blog/2020/12/02/dockershim-faq/
```